### ISSUE TITLE
Capstone Project 

### ISSUE THREAD

**Issue by AaronKip-42** [ds4owd-001/project-Aaron-Kipngeno#3]
@larnsce @mianzg @sskorik01 ,havent received any feedback

**Comment by mianzg** [comment]
@AaronKip-42 Thanks for reaching out to us! @sskorik01 finished the internship and the team is currently just two of us reaching our capacity. To assure you I started to review submitted projects. We will send an announcement and the certificates once all reviews are done. Stay tuned!
